# Generated by Django 4.2.2 on 2023-06-13 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='picture',
            new_name='image',
        ),
    ]
