# Generated by Django 4.2.2 on 2023-06-13 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_picture_recipes_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избраные'},
        ),
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_user_content',
        ),
    ]
