# Generated by Django 4.2.2 on 2023-07-02 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_shopcart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='time',
            new_name='cooking_time',
        ),
    ]
