# Generated by Django 4.2.2 on 2023-07-07 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_rename_time_recipes_cooking_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='description',
            new_name='text',
        ),
    ]
