# Generated by Django 4.2.2 on 2023-07-07 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_rename_description_recipes_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientpass',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_pass', to='recipes.ingredient', verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='ingredientpass',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_pass', to='recipes.recipes', verbose_name='Рецепт'),
        ),
    ]
