# Generated by Django 4.2.2 on 2023-07-07 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_shopcart_recipe_alter_shopcart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientpass',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_pass', to='recipes.ingredient', verbose_name='Ингредиент'),
        ),
    ]
